version: "3.7"
services:
  database:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    user: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    container_name: ginserver
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8085:8085"
volumes:
  data:
